### ISSUE TITLE
My Wallet was hacked... how do I migrate my account?

### ISSUE THREAD

**Issue by gschian0** [hicetnunc2000/hicetnunc#1068]
I woke up to seeing some funds transferred that I didn't transfer... I think I went onto a malicious site on the Tezos network.  I would like to transfer my art that I already uploaded to a new account I am currently transfering my tokens to a new account.  Can someone contact me about figuring out how to remedy this and transfer my identity on hic et nunc to a new wallet?

Thanks,
Gennaro Schiano

**Comment by harduzio** [comment]
Hi Gennaro, the same happen to me, I contact the @TezosBakingBad team in twitter or in Discord and ask them to transfer your profile to a new wallet. They are doing this for me at the moment but I am waiting confirmation because apparently the operation is not completed, I still see my Creations in the profile associated to the old wallet, maybe in the meantime you solve the problem??

**Comment by gschian0** [comment]
Nothing yet… i just transferred my nft’s to a new account and put a disclaimer on my
Old page . I’ll look into transferring the profile!  Thanks for the heads up.

**Comment by harduzio** [comment]
you are welcome,

**Comment by violetforest** [comment]
please let me know if you still need help and I will reopen
