### ISSUE TITLE
Is there anyway to mint executable files along with folders, the same way as Html packages are?

### ISSUE THREAD

**Issue by kino-dome** [hicetnunc2000/hicetnunc#1114]
Hello, I recently found out about hic et nunc and its feature to mint Html pages as .zip files. I have to say that it is super cool and innovative. I was wondering if the same process can be done for Executable packages (an .exe file along with folders for assets etc.)? 

I did find this reddit thread but it doesn't help a lot. I thought to ask here since this project already has a similar feature for Html patches? Is executable minting on the road map by any chance?

Thanks

**Comment by andrevenancio** [comment]
I can think of several reasons why this is a really bad idea.

First one, `.exe` is a windows file. So you are excluding people on other operating systems (mac, linux, iOS, Android, etc), but lest quickly ignore that and focus on the more obvious. This is an extremely dangerous thing to do. You will be able to upload and distribute a virus, a keylogger, there are just so many things I can think off that are a bad idea.

Though the concept of some sort of Blockchain app store is interesting it requires quite a lot of work. Right now you can't publish on any major platform without a rigorous quality and security check and you can think of it as gatekeeping, but as a user you expect a download coming from any trusted online store to be safe.

The only reason we implemented HTML was because we could guarantee that the users would be safe to consume it. The HTML is sandboxed, so its quite hard for things to go wrong. 

I mean, I just saw your portfolio. You're a pretty decent developer. You have to know how dangerous this request is right? Is there anything I might have misinterpred from your request?

**Comment by kino-dome** [comment]
You are totally right about the pitfalls of having non-sandboxed apps roam free on users' computers André. And you are also right about OS compatibility problems that will rise up off this. My question was about a very specific use case tbh and I should have explained that use case I guess. 

I was thinking of how to achieve an ecosystem for digital canvasses and NFTs. Something like https://frm.fm/ but with the power of multi-edition NFTs. In that case the user will be able to still trust the content because it is filtered by a store or entity and at the same time they can have generative/interactive NFT artworks to hang on their walls. One aspect of digital art NFTs I'm not satisfied with at the moment is that they only appear in the format of pre-rendered content. I was so happy when I saw you guys implemented interactive HTML content and thought maybe a very specific scenario like the one I mentioned might be at hand now too.

**Comment by violetforest** [comment]
@kino-dome technical details aside, it sounds on the surface like a great concept in general

**Comment by kino-dome** [comment]
@violetforest Yeah I think so too. Hopefully someone with the know-how can step forward and tell us if such an idea is feasible and if so how :-)
