### ISSUE TITLE
Some of the HTML objkts don't load on Safari

### ISSUE THREAD

**Issue by bilgekaan** [hicetnunc2000/hicetnunc#1177]
Hi! Some of my objkts don't load on ios (safari + chrome) and mac os (safari only, chrome works), I get the error below. They load without an issue on android or windows. I also tried to upload the project somewhere else and it worked on all devices so I believe it's an ipfs issue. 

For example, this doesn't work on apple devices: https://www.hicetnunc.xyz/objkt/316585

This problem only happens when the project is one html file with base64 images.

![Screen Shot 2021-09-18 at 02 20 13](https://user-images.githubusercontent.com/2965842/133864038-33cab1c9-d91f-429a-93be-27cd812d3d65.png)

**Comment by bearcthulhu** [comment]
I was coming here to raise what I believe is the same issue. 

Safari only has experimental support for CSP `prefetch-src` and no support at all for `worker-src` directive. It appears that these content security policies, most notably `worker-src` do not are not enabled in Safari which results in some service worker code not running at all. 
In my case, this results in NFTs using p5.sound.js cannot run sound in Safari on both desktop and mobile devices.

`Refused to load blob:https://ipfs.io/b21acaea-6713-4f1a-9a6a-8d0349ec07e1 because it does not appear in the child-src directive of the Content Security Policy.
p5.sound.min.js:2:21984`

More details on Safari src support: 

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src)

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src)

Suggested fix for worker-src support in Safari, is to set the same policies under child-src which Safari does have support for:

[https://stackoverflow.com/questions/67095697/safari-unable-to-create-worker-from-blob-due-to-content-security-policy-issue](https://stackoverflow.com/questions/67095697/safari-unable-to-create-worker-from-blob-due-to-content-security-policy-issue)

Happy to raise as a separate bug if its a different issue, but it looks like it might be the same to me.

**Comment by clayheaton** [comment]
Thanks for pointing this out @bearcthulhu.

I'm experiencing the same problem. This piece doesn't run on Safari:
https://www.hicetnunc.xyz/objkt/336617

But the same piece on Open Processing, where I developed it, is fine:
https://openprocessing.org/sketch/1270692

Just to confirm, this remains an issue on Safari 15.0, which just released.

<img width="723" alt="Screen Shot 2021-09-21 at 6 30 17 AM" src="https://user-images.githubusercontent.com/205364/134155611-f8510e6f-4a3d-4c10-b175-9c737bf2b15c.png">

Looks like the problematic headers are injected here:

https://github.com/hicetnunc2000/hicetnunc/blob/3f9ac519b59695938773d0fbf9b619b979e6e812/src/utils/html.js#L131

**Some additional notes:**

Note that Mozilla warns against use of `child-src`:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

<img width="753" alt="Screen Shot 2021-09-21 at 6 45 06 AM" src="https://user-images.githubusercontent.com/205364/134157490-ad99d9d8-9672-4720-a6c5-3d769ba42400.png">


Also, `prefetch-src` is experimental on all browsers and not officially supported, according to Mozilla:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src#browser_compatibility

**Comment by bearcthulhu** [comment]
https://github.com/hicetnunc2000/hicetnunc/pull/1281

**Comment by clayheaton** [comment]
@bearcthulhu & @crzypatchwork -- I tested the merged code my minting on staging, over here: https://main.d3cm9lcfrb8gaf.amplifyapp.com/

Here's the objkt I tested:

https://main.d3cm9lcfrb8gaf.amplifyapp.com/objkt/432619

And on H=N:

https://www.hicetnunc.xyz/objkt/432619

Here are the errors that appear in Chrome:

<img width="1078" alt="Screen Shot 2021-10-14 at 7 49 47 PM" src="https://user-images.githubusercontent.com/205364/137410608-44816f37-a4c1-4847-b4e7-67ee50f8b9d7.png">

And Safari:

<img width="1124" alt="Screen Shot 2021-10-14 at 7 52 38 PM" src="https://user-images.githubusercontent.com/205364/137410656-2a9debd6-7684-4bd0-87fb-86e6a8a511db.png">

Looks like there might be an invalid character in the [merge](https://github.com/hicetnunc2000/hicetnunc/pull/1281) -- the comma after `'self'` on line 141.

https://github.com/hicetnunc2000/hicetnunc/pull/1281/commits/28c042167baf219ac4812f4f716ad6431d4590f8#diff-2038d1cff314a89d519cf3c67de2d77db7b668bf2eae2f9dcd0d06aa875120ecR141

**Comment by clayheaton** [comment]
Just leaving this here as a high-level guide to CORS, in case it's useful reference in the future. https://jakearchibald.com/2021/cors/

**Comment by clayheaton** [comment]
This appears to be fixed now.

**Comment by bilgekaan** [comment]
> This appears to be fixed now.

Mine hasn't been fixed yet.

**Comment by clayheaton** [comment]
> > This appears to be fixed now.
> 
> Mine hasn't been fixed yet.

Have you reminted the piece? There is no way to fix pieces that are already minted.

**Comment by clayheaton** [comment]
@crzypatchwork This issue is fixed and the bug can be closed.

**Comment by bilgekaan** [comment]
> > > This appears to be fixed now.
> > 
> > 
> > Mine hasn't been fixed yet.
> 
> Have you reminted the piece? There is no way to fix pieces that are already minted.

I can't burn and remint them. Also, I don't think I would use the same method to upload my objkts.

So it's not possible to fix existing objkts? Are you sure the issues here the same as mine?

**Comment by clayheaton** [comment]
> > > > This appears to be fixed now.
> > > 
> > > 
> > > Mine hasn't been fixed yet.
> > 
> > 
> > Have you reminted the piece? There is no way to fix pieces that are already minted.
> 
> I can't burn and remint them. Also, I don't think I would use the same method to upload my objkts.
> 
> So it's not possible to fix existing objkts? Are you sure the issues here the same as mine?

Hic et Nunc injects HTML into the headers when the piece is minted, before it is sent to IPFS for storage. The only way to fix it, unfortunately, is to re-mint the piece. I reminted 3-4 of my pieces and sent editions of them to collectors who purchased the Safari-incompatible ones. 

The good news is that the bug was fixed a few weeks ago. 

The only way you'll be able to see if the fix works for your piece is to remint it, I'm afraid. I'm 99.9% this is the same issue as yours. The images in your original post show the CORS headers that were incompatible with Safari. At the time you originally minted, the Safari fallback was not in the injected headers. It is there now, but is only inserted when the piece is minted & I believe that objkts cannot be modified once they're stored.
