### ISSUE TITLE
Can't upload .glb file, got an error

### ISSUE THREAD

**Issue by malboyoo** [hicetnunc2000/hicetnunc#129]
here is the message when i click on "Upload OBJKT" and i select the file: https://prnt.sc/10lh53h

it was working yesturday, i don't really understand.

**Comment by andrevenancio** [comment]
This is probably down to the .glb you're trying to upload. I have a .glb that I use for testing on the platform and I never get the mimetype undefined. Can you share the file you're using?

**Comment by mihnor** [comment]
Hello there, I just found a bug yesterday that made me spent 12h straight trying to upload a .glb or .gltf.

When you use Apple Silicon M1, and uses browsers like Safari and Chrome you get an error message when you try to mint that says “FILE FORMAT INVALID!”

<img width="1440" alt="Screenshot - 2021-04-22 15 00 08" src="https://user-images.githubusercontent.com/7723717/115884692-90803a80-a425-11eb-8955-59f32606f448.png">


In the documentation 3D OBJKTS needs to be : less than 40 MB, GLB or GLTF. Doesn't have any kind o limit of tris, or kind of compression.

IS JUST THAT

The error was happening after preview, when I tried to mint. as you can see in the screenshot.

I tried many different approaches, thinking that problem was my file. But don't.
I tried to mint using safari and chrome for iOS, with the same files tried before and twice I got a request to my wallet. So I discovered that wasn't my 3d object.

So I thought that could be something correlated to the browser, cache or something...

I installed Firefox on my MacBook, installed a wallet extension. 
And I just clicked to mint and worked flawlessly.

BUT, I just found another BUG

When using Firefox browser, in the profile page at hic et nunc that has interactable 3d OBJKT, the ram usage passes 5GB and crashes completely. This happened 3 times yesterday ( I will report in a proper issue )
