### ISSUE TITLE
header links onClick handlers vs route handling

### ISSUE THREAD

**Issue by Anemy** [hicetnunc2000/hicetnunc#181]
https://github.com/hicetnunc2000/hicetnunc/blob/main/src/components/header/index.js#L24
<img width="579" alt="Screen Shot 2021-03-18 at 12 01 42 PM" src="https://user-images.githubusercontent.com/1791149/111622956-b7719e00-87e1-11eb-9de2-b0195fe26ac4.png">

Is there a reason that a few of the header routes are buttons without the `to` prop?
I think it might be nice to have it more of a traditional route so on right click this is possible:
*current behavior:*
<img width="348" alt="Screen Shot 2021-03-18 at 11 57 42 AM" src="https://user-images.githubusercontent.com/1791149/111622570-43cf9100-87e1-11eb-9e86-09f9ddbfc23f.png">
*desired behavior*
<img width="311" alt="Screen Shot 2021-03-18 at 11 57 32 AM" src="https://user-images.githubusercontent.com/1791149/111622567-4336fa80-87e1-11eb-9fe8-0a66ac2c2a00.png">
(I love opening many tabs). Happy to open a pr if its something desired.

Thanks for making this cool site! Stoked for the project.

**Comment by andrevenancio** [comment]
the reason is on the method `handleRoute` itself.

This page is a single page application. there's no refresh on the browser when the user changes routes. So clicking on that button you highlited does 2 things.
1) closing the menu by changing a prop on the context (legacy)
2) handles a route change.
