### ISSUE TITLE
Random feed

### ISSUE THREAD

**Issue by sp94** [hicetnunc2000/hicetnunc#185]
Currently we show the latest OBJKTs and soon we will show the community favourites using hDAO votes; a randomly ordered feed could be fun and aid (re)discovery of older OBJKTs

Based on squinonescolon's post on Discord
https://discord.com/channels/759930487946215444/812076126541316136/822103566051311636

**Comment by Quasimondo** [comment]
Yes, I would love to see that. Ideally also with the option to only show random works that are still available and for sale.

**Comment by Quasimondo** [comment]
There is also always the option to build a temporary "companion" site. Sorry for pushing my own experiment here, but just to give you an example: http://here-or-there.glitch.me/

**Comment by squinonescolon** [comment]
Good gracious, that's clever. I think a companion site might be a good idea since it helps to keep the main site streamlined and retain the current visual while keeping minting separate from gallery. Although one has to think about how collectors would feel having to visit two different sites or would they just visit the gallery and buy there?

**Comment by Quasimondo** [comment]
I think it is a good method to test out different interface methods in parallel without interfering with the regular development, but some of them might possible be integrated into the site later on.

In order to retrieve the data from hic et nunc and to generate the thumbnails I wrote a little script that was further improved by @schwittlick
https://gist.github.com/schwittlick/a6a839b211060dcbf766d24b99e0ad1a

**Comment by sp94** [comment]
Looks like this has been added, thanks!
