### ISSUE TITLE
Add Intersection Observer to elements

### ISSUE THREAD

**Issue by andrevenancio** [hicetnunc2000/hicetnunc#194]
Add intersection observer api support to rendered media types.

A Video should only play if its in view, and it should stop if it gets out of view.

Potentially apply the same concept to every element in an effort to only render it once it's in view

**Comment by haustraliaer** [comment]
I've been working on a PR using a virtualised list - which only _renders_ things (at the react layer) as they scroll into view.

It's still a bit buggy and also ignore me playing around with the design a bit :P - but you can check it out here:

https://github.com/haustraliaer/hicetnunc/tree/virtual-feed

I'll probably keep going with this until I'm happy with the layout and design and then submit it if you think it's something worth doing.

Some issues I've come across... which aren't unsolvable - or perhaps are just trade offs:

- the items when they re-render flash a bit and reload the media 
- we kind of do have to go back to a fixed viewport with the footer, otherwise the virtual grid won't use the "browser's" natural scrollbar.
- I'm not sure if it'll work on mobile that well, might have to switch it out at a certain viewport width
