### ISSUE TITLE
Hi-res images are publicly displayed to everyone on the site - full size and all

### ISSUE THREAD

**Issue by preslavrachev** [hicetnunc2000/hicetnunc#197]
This was quite unexpected to me, both as a visitor of the platform, and as an artist, whose hi-res assets are now publicly exposed and ready to be ripped off at any time. I half-expected that what I am seeing is just thumbnails, until I realized it was the hi-res versions of my works.

This issue has been mentioned a couple of times under different forms. Some people asked for the ability to share private links to hi-res assets with the buyers. 

What I can propose is something much simpler. For all visitors, run each image asset through a scaling proxy. This will both dramatically improve the experience for end users and will reduce the unauthorized copying of assets. For those that already have an asset in their collection, display the full res asset, so that they can save it. Simple and relatively easy.

How does that sound?

**Comment by crzypatchwork** [comment]
there's the possibility of integrating displayUris in the metadata, as well locking other formats on certains conditions. it would be interesting to explicit the actual state of the dApp. but it would be needed indeed an upgrade in the actual metadata that's being used. any insights are welcome in this sense.

**Comment by djangobits** [comment]
Doesn't sound good in my ears. It would mean that the collector could not really inspect the art he will buying a token from. Then, some pieces might turn out very ugly after rescaling and recompressing. As these pieces can be sold and resold over and over again, there is no way to make sure they won't be out in the wild anyway. 

But as they are NFT's the token ownership defines who is the owner. That's THE central part of NFTs (and probably the most disputed as well), but that's what we need the token for, to set a pointer for the ownership. The token is the solution to that problem you bring up. That is all NFTs are about about. So nope, it's not necessary to hide or cripple the piece.

**Comment by Quasimondo** [comment]
> How does that sound?

This might sound strange for people who are new to NFTs, but it is how it works. You mint the original work and it gets stored on IPFS where it is available publicly. Putting in some scaling proxy would just be an obfuscation and not prevent bad actors to get your assets anyway. But I do see a benefit for using scaling or thumbnails as a way to save bandwidth in the browsing and discovery pages.

In order to do what you have in mind an updated smart contract would be required that allows to "lock" additional content that only becomes available to the owners of the NFT. rarible.com has such an option, but I lack the technical expertise to know how it works under the hood and how safe it is, since it is very difficult to store secrets on the blockchain.

**Comment by skenaja** [comment]
> But I do see a benefit for using scaling or thumbnails as a way to save bandwidth in the browsing and discovery pages.

This. A CDN that does scaling/resizing might help (I think [Fleek](https://fleek.co/storage/) offers this for IPFS $$$)

As a point of comparison, Kalamint.io has already hit this problem, its homepage was originally just loading the original images, with many >40MB leading to [complaints of >1GB of data being consumed](https://www.reddit.com/r/tezos/comments/mdddqu/kalamintio_loads_over_1gb_of_data_during_a_single/). They're now lazy loading the artwork which helps somewhat, but if you doomscroll their explore page, make sure you're not on a limited data plan, the full images do still get loaded!
