### ISSUE TITLE
TIFF causes broken link, unable to burn

### ISSUE THREAD

**Issue by JonSaysRelax** [hicetnunc2000/hicetnunc#204]
Hiya, I tried minted a TIFF image twice and it failed to preview and show as a proper image. I suceeded with a jpg the 3rd time but now i cant burn the other 2 failed ones. Is there a way to remove it / burn it? Thanks
![Screen Shot 2021-03-21 at 1 52 29 AM](https://user-images.githubusercontent.com/81062922/111892769-462c2800-8a39-11eb-9756-452424b9a9e5.png)

**Comment by toliver93** [comment]
Hey I'm getting this issue too as a user. TIFF isn't working on the UI in Chrome but seems to be working for Safari. Please can you update so it works on Chrome

**Comment by andrevenancio** [comment]
Couple of notes:
1) Tiff is currently only supported by Safari as far as I can [tell](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#tiff) Which is a limit that we have no control over.

2) The tags should have been separated by commas as indicated in the description on the mint page.

You should be able to go to your profile choose this objkt in question, click SYNC and then click "Burn" That should remove the objkt from your profile.

I would try it in a couple of days though because that functionality is still being updated as we speak. And even I personally have a few minted objkt that I want to delete.
