### ISSUE TITLE
Licensing and credit attribution on Interactive NFT

### ISSUE THREAD

**Issue by andrevenancio** [hicetnunc2000/hicetnunc#255]
Hi team!

Following a conversation some of us had on Twitter earlier, I though it would be healthy to have an open conversation weighing in the pro's and con's on licensing and credit attribution on interactive NFT's. So we can decide together what's the best approach on attributing credit when credit it due (if credit is due), and try to be reasonable about what constitutes a copyright issue and what doesn't (e.g.: can I include someone else's image and use it as a seed for my generative NFT). So think of this from the point of libraries (three.js, pixi.js, p5.js, gsap, etc), but also think of this from the point of view of templates (people who create templates for other people to use) and finally assets (images, text, etc).

We're open to adjust the UI to accomodate for any requirements that might come out of this conversation. hic et nunc is made by all of us to all of us, so all opinions are valid. However its always nice to put ourselves in other people shoes, and consider both angles.

**Comment by spite** [comment]
To be clear: I added a CC-BY-SA license to the NFT. It could have been a LICENSE file inside the zip. I think we need some license explicitly stated in each NFT, so instead of going with a code license, i checked on the CC site and those two were the two recommended. May be not necessarily the best, but should do for the NFT.

The gist was to simplify people getting to the code and work from it, instead of fishing it out of the IPFS node. The license in the HTML is NOT the license of that code. I'm not even sure if a gist can have license. 

Anyway, if the template for effects with WebGL, threejs, p5, shadertoy, etc. becomes a repo that people can work from, that will need a license and it could be MIT or similar.

But the implications of each generated piece being sold and potentially resold are important.

**Comment by davidpaulrosser** [comment]
I wasn't attacking you at all so please don't take this personally. The main point I was trying to get across is that right now people are relying on us, the experienced web developers to help them and provide them with a canvas to create NFTs. Licenses around code definitely needs discussion on the best approach.

**Comment by davidpaulrosser** [comment]
None of us created the WebGL api (not to my knowledge) yet its an integral part of the toolkit we use to make our artwork. So when it comes to licenses I feel offering a minimal template should be offered for free as a gesture of good will from our community.

**Comment by Quasimondo** [comment]
My personal two cents:
- I think we have to distinguish between auxiliary 3rd party libraries, frameworks or templates and the code that makes up "the work"
- For the libraries the conditions are pretty clear in my eyes since they just inherit the license they came with. It is in the responsibility of the person who mints the NFT to respect those licenses and provide credit inside the code or in the public description depending on what the license says
- For code that makes up the work itself I would assume by default that this is "all rights reserved", "no reuse", "no derivative works" unless it is explicitly stated by the creator.
- Unless a work is never put on the market I think NFTs are always "commercial use" no matter if they are given away for 0 tez, since they can always be resold later for a price on the secondary market.

Otherwise in particular with generative art we will run into the situation that someone just copies the code, changes the background color and makes their own NFT with the argument "well, it's not an identical copy". Remixes are all nice, but I still believe that they always need the consent of the person who's work gets remixed.

As for general etiquette: I believe that is at everyone's personal discretion, but of course it is desirable that if somebody else's work was instrumental in the inspiration or important parts of someone's code was reused to give credit. Whether that is in the description or hidden in the code I would make dependent on a case-by-case decision. I think it is also good form to mention it in the social media "marketing".

**Comment by andrevenancio** [comment]
> None of us created the WebGL api (not to my knowledge) yet its an integral part of the toolkit we use to make our artwork. So when it comes to licenses I feel offering a minimal template should be offered for free as a gesture of good will from our community.

Should we require people to add, lets say three.js if they're using three.js? I fear there's not an easy solution to cover all cases, but I would be upset if someone picks up some content I've done (lets say a shader) and copies it, changes the values and calls it their own.

Or if they use an image I created on their NFT and apply a shader to it. Its those cases I personally struggle to point the finger. I know Art comes from everyone inputs and I can get inspired by someone's work and base my work from someone else's work and call it my own. But then judging if my work trully belongs to me can be subjective. Hence this type of disputes normally end up in court.

There's always going to be bad actors, we're not trying to solve that, but I think we should try to figure out a common best practice.

**Comment by spite** [comment]
> offering a minimal template should be offered for free

The code in the gist is free to use -supposedly a gist is like a git repo under github terms.
The license in the HTML is not the license of the code.

The CC-BY-SA is meant for the NFT to have a license but it can be changed, same as any other part of the code (that would be the part " "all rights reserved", "no reuse", "no derivative works"). Ideally we can provide some guidance or a license file. It should probably apply to other formats as well.

**Comment by Quasimondo** [comment]
> Or if they use an image I created on their NFT and apply a shader to it. Its those cases I personally struggle to point the finger. I know Art comes from everyone inputs and I can get inspired by someone's work and base my work from someone else's work and call it my own. But then judging if my work trully belongs to me can be subjective. Hence this type of disputes normally end up in court.

A measure I use personally is to ask myself how I would feel if somebody did the same thing with my work that I am doing with theirs. Of course this is not a perfect measure since everyone feels different about their work and how it is being referenced. 

We are dealing with one new factor here that was not as prevalent in the previous years of free open source sharing and that is unfortunately money. Money makes things ugly. Whilst one might still feel okay that a fork that someone made of one's code gets more stars or likes than one's own it will create envy and pretty bad feelings (or worse) if someone forks your code, makes some trivial changes to it and sells it for a lot more than you because they have a bigger social network or are just more lucky or famous.

**Comment by davidpaulrosser** [comment]
> > offering a minimal template should be offered for free
> 
> The code in the gist is free to use -supposedly a gist is like a git repo under github terms.
> The license in the HTML is not the license of the code.
> 
> The CC-BY-SA is meant for the NFT to have a license but it can be changed, same as any other part of the code (that would be the part " "all rights reserved", "no reuse", "no derivative works"). Ideally we can provide some guidance or a license file. It should probably apply to other formats as well.

I agree! We could propose a LICENSE file that should be embedded in any sort of web based NFT. One that could state the following maybe:

* Asset ownership
* The nft artist agreeing by what they upload doesn't infringe anyones copyright

**Comment by spite** [comment]
> someone forks your code, makes some trivial changes to it and sells it for a lot more

i think for many open sourced libraries it's the case that users in commercial projects might end up making way more money than the creators/mantainers... in that sense my experience with derivative works with commercial purpose is very limited.

i'd imagine that someone buying an NFT using a set of libraries "inherits" the licenses via whatever stipulations about commercial work each library has, so it follows that we should provide a way to state those clearly, and what do they mean for the buyer. also, IANAL

**Comment by veqtor** [comment]
Also, there IS a license field in the FA2 token standard, so any license should be embedded there, don't know if it's supposed to be a string or ipfs-hash

**Comment by davidpaulrosser** [comment]
Consider the following case: Someone blatantly infringes the copyright and work from someone else. How would hicetnunc / any other platform react to this. Would the platforms de-list or hide it, or would they display some sort of message saying this NFT doesn't comply to the terms and service?

I guess there isn't a killswitch / self destruct technique for the NFT to react to if it infringes copyright?

**Comment by spite** [comment]
There are a few filters. They're manually edited atm https://github.com/hicetnunc2000/hicetnunc/tree/main/filters

**Comment by Quasimondo** [comment]
> I guess there isn't a killswitch / self destruct technique for the NFT to react to if it infringes copyright?

The only person who can burn an NFT is the current owner. There is no way hicetnunc can do that. The only measures that are available and that are already being used for copyminters is to ban a wallet and to hide NFTs that are associated with that wallet from the site. Also these works get unpinned from IPFS and are likely to get garbage collected subsequently.

**Comment by Quasimondo** [comment]
To report a suspected copyminter or a copyright infringement please use the "report abuse" channel on the hicetnunc discord, but please provide evidence that allows others to verify the claim:
https://discord.com/channels/759930487946215444/818877118489690182

**Comment by vorg** [comment]
Isn't that you buy the visual experience (or rather signed version of it) rather than the code? The fact that code is available is for viewers pleasure only and doesn't give you any rights to modify it unless explicitly stated. Somehow the same discussion could be made about people modifying your SVG or photoshopping your JPGs. 

It would imply exactly what @Quasimondo
> For code that makes up the work itself I would assume by default that this is "all rights reserved", "no reuse", "no derivative works" unless it is explicitly stated by the creator.

Also it might be issue mostly with smaller scripts and i don't think anybody will try to reverse engineer 700kb minified bundle js :p

What code does though is possibly much easier way to learn the technique and creatively apply it without even copying a single line. I don't think there is licence that would protect you here. Just see how many cube subdivisions are there on different NFT platforms earning $$$. I personally don't mind works that are clear inspiration or recreation of other people's work exactly because money involvement makes it too messy unless it was a collab. Example [here](https://twitter.com/marcinignac/status/1068500531897749505)

**Comment by davidpaulrosser** [comment]
> There are a few filters. They're manually edited atm https://github.com/hicetnunc2000/hicetnunc/tree/main/filters

I think we could try and solve this in a few steps.

Website:
1. Add a disclaimer notice and an agreement checkbox when minting NFTs. The disclaimer notice points to a Terms and Conditions file on the Github. If people violate the T&C's then the filters would mask out the NFT / wallet.
2. Figure out what kind of embedded License agreement should be shipped with the code, if required.

**Comment by andrevenancio** [comment]
What we noticed is that copyminters just move to new wallets. Its really tricky to get right. So far those filters are the only solution we have, and they have to be manually added by someone on Github. @djangobits has been kind enough to be in charge of that. I think in the future we will be able to take some of the burden from him by implmenting a report system and then we can have more eyeballs over from the community checking content. But that's a topic for another Github issue :)

Its interesting to know that there's a license field on the blockchain, which we can look into, but it doesn't cover everything. If you're using multiple libraries with multiple licenses and if they require you to credit them, then having 1 license field on the blockchain doesn't necessarly address that.

I wonder if we should in fact either include a LICENSE.md file with all the licenses and credits one wants to attribute and on the UX we have a "view license" button that links to that LICENSE.md file on the IPFS directory?

**Comment by davidpaulrosser** [comment]
> Isn't that you buy the visual experience (or rather signed version of it) rather than the code? The fact that code is available is for viewers pleasure only and doesn't give you any rights to modify it unless explicitly stated. Somehow the same discussion could be made about people modifying your SVG or photoshopping your JPGs.
> 
> It would imply exactly what @Quasimondo
> 
> > For code that makes up the work itself I would assume by default that this is "all rights reserved", "no reuse", "no derivative works" unless it is explicitly stated by the creator.
> 
> Also it might be issue mostly with smaller scripts and i don't think anybody will try to reverse engineer 700kb minified bundle js :p
> 
> What code does though is possibly much easier way to learn the technique and creatively apply it without even copying a single line. I don't think there is licence that would protect you here. Just see how many cube subdivisions are there on different NFT platforms earning $$$. I personally don't mind works that are clear inspiration or recreation of other people's work exactly because money involvement makes it too messy unless it was a collab. Example [here](https://twitter.com/marcinignac/status/1068500531897749505)

In reality people are buying the visual experience over the means in which it was made. I think it comes down to what you're creating and uploading is purely your own original work, and if it uses some technology you don't have the right too, what does that mean for the one purchasing the NFT.

**Comment by davidpaulrosser** [comment]
> What we noticed is that copyminters just move to new wallets. Its really tricky to get right. So far those filters are the only solution we have, and they have to be manually added by someone on Github. @djangobits has been kind enough to be in charge of that. I think in the future we will be able to take some of the burden from him by implmenting a report system and then we can have more eyeballs over from the community checking content. But that's a topic for another Github issue :)
> 
> Its interesting to know that there's a license field on the blockchain, which we can look into, but it doesn't cover everything. If you're using multiple libraries with multiple licenses and if they require you to credit them, then having 1 license field on the blockchain doesn't necessarly address that.
> 
> I wonder if we should in fact either include a LICENSE.md file with all the licenses and credits one wants to attribute and on the UX we have a "view license" button that links to that LICENSE.md file on the IPFS directory?

Thats a good idea. It would be cleaner and future proof to have a link to a license somewhere that is maintained by the community. So any NFT, regardless of when it was created still retains the most recent and agreed license.

**Comment by veqtor** [comment]
I think we should let artists choose between a few licenses, including ones that state that owners may remix the work and mint remixes while they own it

**Comment by neilmangan** [comment]
Generally speaking, it is important to distinguish between the copyright/license terms in the code used to generate the artwork and copyrights in artwork (or artifact) itself.

When considering these issues, you will want to review the generative code license to see if there are any particular limitations or attribution requirements for output artwork. For amendments to the generative code itself, this would be subject to the usual open-source license terms, such as attribution and any copyleft restrictions on commercial use, etc.

Forgetting any unique issues flowing from generative artwork source code and the unique way that genertive artwork is created, there is nothing particularly special about copyrights in NFT artwork/artifacts. It’s just another medium for marketing and recording copyright rights and licenses.

The creator of artwork would normally need to ensure that their artwork (artistic expression) does not infringe upon any pre-existing works. Any marketplace facilitating the sale of artwork - such as through NFT mediums - would normally want to take reasonable steps to ensure that the seller is either the lawful creator of work free from third-party claims or has acquired copyrights from that person. 

Marketplaces will need to develop mechanisms for third parties to report (suspected) copyright violations and to take down listings suspected of infringing copyright. While limited in value, creating deny lists for specific IPFS hashes would be an interesting way to at least show that a very specific infringing artifact is prohibited in the marketplace (assuming there is no administrative right to burn the NFT in the smart contract).

It can be difficult to track down someone selling counterfeit NFTs. It will often be easier to go after the marketplace itself for any profits made and contribution to damages caused by facilitating unlawful sales.

The creators/sellers of NFTs will normally want to protect their intellectual property rights in the works by clearly stating whether the sale of the NFT is meant to convey ownership in the underlying copyrights (which becomes problematic when NFTs are replicated across a series), or more commonly, that the NFT merely grants a license to use the NFT artifact for a specific or limited purpose. The protection of these rights is often intimately connected with a work's value.

For example, does purchasing an NFT give a buyer the right to use the image for any purpose? For commercial purposes? Or is it merely intended to let the user enjoy the art for non-commercial purposes? How are these purposes defined? Does a person's license end when they sell their NFT? Are there any royalties payable back to the original artist of the copyright owner on the sale of the NFT?

Looking at the developing Tezos standards, TZIP-16 (Contract Metadata - WIP) currently provides a reserved field for “license”, however my understanding is that this is intended to refer to the license in the contract code itself, which would normally (hopefully) be open-source. This could use further clarity.

TZIP-21 (Rich Metadata - DRAFT) is being designed to provide a richer set of metadata that may help resolve some of these issues. For example, this schema includes a “rights” string and a “rightURI” string that should allow creators/sellers/marketplaces to attach or link to detailed licenses and other information about what purchasers can and cannot do with their NFTs.

Anyone creating or selling NFTs, intending to purchase NFTs for commercial use (other than the simple resale of the purchased token), or running a marketplace that may facilitate the sale of NFTs, should get legal advice specific to their jurisdiction. There is bound to be copyright litigation in this area as the market matures - and money start flowing - and there are some straightforward things that can be done to limit risks.

Everything is moving quickly right now, but hopefully, best practices and standards will evolve over time.

(**p.s. THIS IS NOT LEGAL ADVICE!**)

**Comment by idlebit1** [comment]
This is what I use:

```
My NFT Name
Copyright 2021 My Legal Name
NFT License 2.0 [nftlicense.org]
THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
```

NFT License 2.0 is really good and worth knowing about. It gives the buyer a fair amount of freedom while still giving the creator control over their intellectual property. (I am not a lawyer! This is not legal advice.)

**Comment by kellymilligan** [comment]
In addition to figuring out this license stuff; I'd love the ability to include additional wallet addresses that can receive a royalty for any transaction on the token. 

Similar to current "Artist Royalties" approach, where up to a certain percentage can be divvied up among the artist **and** other wallets on resale. Is this possible?

Say I minted an interactive NFT using Three.js:
- 10% artist royalty
- 5% to @mrdoob (or maybe the project itself could have it's own wallet for royalties, so that it's not just going to an individual when so many others have also contributed)
- 5% to some other MIT licensed package that's critical to the work
- Up to a max of 25% in total

I'd like this as an (optional) financial nod to the OSS project maintainers that have enabled the artwork creation.

**Comment by codewithfeeling** [comment]
We released our [interactive music player](https://www.hicetnunc.xyz/objkt/11192) last week and the response has been great. A guy just asked me on Twitter: "Beautiful piece! Do owners have rights to make new things with the audio?"

We actually don't mind if people do actually want to use the audio transformatively but are wondering how we can do this. Someone could just take all the tracks and use them to make a movie soundtrack for which they charge $100,000 (hypothetically) which obviously wouldn't be ideal for us... but if someone else wants to use our track as a soundtrack for another piece on hicetnunc, properly credited, then bring it on. Collaborations are something we are excited about.

It looks like there's going to be no option but to build a licence into the work.

**Comment by staus** [comment]
Hey, haven't had time to read through the whole thread, but really love that this conversation is happening.
Wanted to share a case example of exactly the problem you're describing. Maybe you all know it, but doesn't seem to be mentioned: 
MarbleCards features a thumbnail of any URL inside their nfts, but of course that's most of the time other artists pictures. Simon Stålenhag called them out and the exchange is quite telling.
[https://twitter.com/marble_cards/status/1369680858815340548](https://twitter.com/marble_cards/status/1369680858815340548)

**Comment by jimfetterley** [comment]
HI all-

(EDIT here):  I have removed parts of my initial post to take my 1st personal account out of the discussion and update references as I've been learning and getting educated on the issues with copyright I was experiencing and thinking about. Of course, appropriation art can be sold on the blockchain, and it may hold up to a Fair Use case if a copyright holder would like to send a cease and desist or legal action.  This is totally separate from the copyminter issue which is clearly copyright infringement, obviously.  It's the exact same laws as in traditional art market, and after some time exploring this, it is quite honestly not so interesting to me personally anymore- haha!  I did want to update this post with a link to a recent early draft article by Brian Frye that goes into the issue of copyright in NFTs and traditional art markets and how conceptual art has been sold for 50 some years.  Now I actually know how to post a link on here, I will update links below!- thanks for your patience with me. [https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3829399](url)

I find it clear that the traditional art markets have allowed appropriation/ remix art to be sold with some exceptions, but for the most part, for over a 100 years- if a piece of cultural work provides parody or criticism, it is in the category for Fair Use.  My question is, does this apply to selling the piece on the blockchain?  I asked my friend, @brianlfrye, who is a legal scholar and artist, and he quickly replied- that he is writing on this subject as we speak because this very question is part of his legal scholarship and art practice. Here is a podcast from last week where the author, @martha_buskirk (recently wrote a book on copyright and artwork) interviews Brian on the subject of his regular role he is often  finding himself in- as the lawyer friend of artists and institutions who have questions about copyright and intellectual property for artwork, films, and videos.  I found this to be a great introduction to Brian's work as a resource to this community. He is often providing free consultation and legal advice but also is working towards a legal understanding of such issues for NFTs, etc.  Here is that podcast for those interested in knowing more about Brian as a resource. I have introduced him to the community and now, I'd like to introduce you to him [https://shows.acast.com/ipse-dixit/episodes/brian-l-frye-on-conceptual-law](url)

On a second note, as a film/ video artist working with appropriated materials for over 25 years, I always go back to a foundational film that continues to inspire and inform me surrounding the case of Island records vs. Negativland.  The 1995  film, Sonic Outlaws by Craig Baldwin is something that still informs and inspires me to this day- covering that case, and other artists at the time, working with those same anti-copyright issues.  It is here for free to view at [https://archive.org/details/dom-25571-sonicoutlaws   ](url)

Thanks for providing this space for discussion, and participation. Hicetnunc is truly a breath of fresh air in the digital landscape.  Look forward to following and discussing this topic more!  

Cheers, Jim
