### ISSUE TITLE
Burned OBJKT gets filtered on creations page even if only 1 edition out of many got burned

### ISSUE THREAD

**Issue by matangkuwago** [hicetnunc2000/hicetnunc#280]
I saw that someone burned 1 edition of my objkt (there are 100 editions) and the objkt no longer appears on my creations page.

**Comment by LeithBA** [comment]
I checked the code. Currently it is checking if one of the owners of each object is the burn address. This is quite an issue since anyone can burn any object they own.

I wonder if it would be possible to check the blockchain for the previous owner (before the burn address) and see if it is the creator indeed before filtering out the object.

**Comment by matangkuwago** [comment]
Or I was thinking if maybe it can check if all editions are owned by the burn address before filtering. I don't know if that's more simple.

**Comment by LeithBA** [comment]
If you did that, you would not be able to hide an object by burning it if you've already sold at least a copy

**Comment by andrevenancio** [comment]
I think this is related with a bug I just fixed. However, @matangkuwago please provide more information like your wallet address. otherwise closing this.

**Comment by matangkuwago** [comment]
For example this object doesn’t appear on my creations page because someone burned 1 edition: https://www.hicetnunc.xyz/objkt/13688

**Comment by skenaja** [comment]
Seen with `tz1cx7pUAJLuuhSpQ7tgsfE63qRkq7YnJyq2` and objkt `15759`.

Confirmed that `tz1burnburnburnburnburnburnburjAYjjX` is listed as one of the collectors.

**Comment by andrevenancio** [comment]
Having the burn address in one of the collectors doesn't exclude it from your profile.

The only time we're excluding nft's from your profile is it your're the creator of the NFT and if that NFT is on the burn address.. That feature has been reverted today by @crzypatchwork so I'm not sure how to fix this.

**Comment by skenaja** [comment]
> Having the burn address in one of the collectors doesn't exclude it from your profile.

It did (before it was commented out/reverted in the latest hotfix to `pages/display/index.js` which has turned off all burn item filtering). The response of the `contract/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/holders` API call in [L76](https://github.com/hicetnunc2000/hicetnunc/blob/dcc6556672200e020bbc3ffcba633fdbd9c64ae3/src/pages/display/index.js#L91) contained at 1 instance of the burn address (rather than the looking at how many editions were held) so index.js [filtered out](https://github.com/hicetnunc2000/hicetnunc/blob/dcc6556672200e020bbc3ffcba633fdbd9c64ae3/src/pages/display/index.js#L89) it out.

This API call also [lists all burnings](https://api.better-call.dev/v1/tokens/mainnet/transfers/tz1burnburnburnburnburnburnburjAYjjX?token_id=15759) of editions for this token. It currently lists `amount: 1`

This is less than the number of editions originally minted [which was 300](https://staging.api.tzkt.io/v1/accounts/tz1cx7pUAJLuuhSpQ7tgsfE63qRkq7YnJyq2/operations?entrypoint=mint&parameter.token_id=15759
), (also obtainable from internal metadata API `https://51rknuvw76.execute-api.us-east-1.amazonaws.com/dev/objkt` as `total_amount: 300` so the filter should only take place if burn address is holder of `total_amount` copies.

**Comment by mikesizz** [comment]
Hello! I have a PR in review to deal with burned NFT's. It doesn't seem like a big problem to hide a brand new NFT that was burned (just ensure that the burn addr has all of them). What I am trying to finalize is when an objkt is owned by one other person and the issuer burns the rest of their copies. Is this a case where we would also want to hide it from the creations list?

https://github.com/hicetnunc2000/hicetnunc-api/pull/23

**Comment by matangkuwago** [comment]
It looks like this is now fixed! Thank you @LeithBA, @andrevenancio, @skenaja, and @mikesizz + @crzypatchwork for the fix!
