### ISSUE TITLE
OBJKT sold, but doesn't show the collector's address

### ISSUE THREAD

**Issue by neverhood311** [hicetnunc2000/hicetnunc#363]
There are two OBJKTs of mine that sold today, but I'm not able to see the address of the collector:
https://www.hicetnunc.xyz/objkt/15099
https://www.hicetnunc.xyz/objkt/19714

What's going on?

**Comment by neverhood311** [comment]
I did some digging, and it looks like the buyer (tz1YNUNArBDYWu8evZj73HR9vE6y5FQkaj5M) purchased several of my OBJKTs, then was added to the wallet blacklist two hours later (https://github.com/hicetnunc2000/hicetnunc/commit/54c2a2709f0edca1069a0939e01076b6249261db, committed by @djangobits). However, there's no reason given for why they were added to the list.

This brings up a concern. If a wallet is added to `filters/w.json`, does that completely ban them from any activity on the platform, including re-selling items they've purchased?

**Comment by andrevenancio** [comment]
@djangobits ☝🏻

**Comment by codewithfeeling** [comment]
I think this might have happened to me. I purchased multiples of https://www.hicetnunc.xyz/objkt/19486. I swapped one, and can in fact still see the swap button... but my ID is not in the collectors list and the asset is not showing in my wallet.

![image](https://user-images.githubusercontent.com/262516/113400501-cdfb2600-9399-11eb-8dbe-38481dd7109d.png)

Swap showing, but not in the collectors list (tz1YJv...hbUQ)

![image](https://user-images.githubusercontent.com/262516/113400561-e66b4080-9399-11eb-9c6e-50a922fa3d42.png)

Asset not appearing in search in wallet (searching by title)

![image](https://user-images.githubusercontent.com/262516/113400613-fc790100-9399-11eb-859d-cf5a37893e9a.png)

**Comment by oldominion** [comment]
So you're jenHP! Pleases top taking so many copies, especially of free issues. I've missed out on pieces I really wanted to own because you have 10 of them. Take 2 and give other people a look in.

**Comment by skenaja** [comment]
@neverhood311 there was an issue affecting an upstream API which meant there was a delay in the collectors tab getting updated. This has now been resolved, and the collectors should now be showing up.

**Comment by codewithfeeling** [comment]
I can confirm that I can now see my purchases in the collector tab for the piece in question.

> So you're jenHP! Pleases stop taking so many copies, especially of free issues. I've missed out on pieces I really wanted to own because you have 10 of them. Take 2 and give other people a look in.

I'm not "jenHP" and have never taken more than one free copy of anything. My ID is tz1YJv...hbUQ - the whole point of my post was that my ID was NOT showing up.

**Comment by mescalina** [comment]
> This brings up a concern. If a wallet is added to `filters/w.json`, does that completely ban them from any activity on the platform, including re-selling items they've purchased?

Banned addresses cannot interact anymore with the website UI but I guess they can send a token they bought to a new whitelisted address from their wallet if they want to be able to resell it, and if they don't copymint again with the new address I suppose they are fine and the items are back on the market. Somebody corrects me if I'm wrong.

**Comment by veqtor** [comment]
@djangobits , any recollection on why tz1YNUNArBDYWu8evZj73HR9vE6y5FQkaj5M was banned?

**Comment by djangobits** [comment]
@veqtor yes, this user is know under the name of owsleyseeds / owsleybeats. He was one of those who selfishly took dozens of freebies during objkt4objkt. While I thought that was not enough for a ban (some users requested it), I confronted him with the selfishness of his actions on discord. owsley decided that he would just start to throw shit after me instead of offering an explanation. A heated dialogue started on discord during which I decided to ban him from the UI, resulting in death threats towards me coming from his side. One could argue that I wouldn't have the right to ban him because he didn't mint copies. Still I do think that he had proven unacceptable behaviour and a ban is well deserved. This might need further discussion, but his actions post-ban speak volumes. If you need to know more, check twitter.com/owsleybeats. On demand, I'd also puplish the discussion I had with him on discord. Technically he still owns these NFTs (they are on the blockchain, nobody can take em from him) and he can also swap them when visiting the OBJKTs page, but he won't see his own profile or his own colection on hicetnunc.xyz. Crazypatchwork is informed about this and supports the decision.

**Comment by veqtor** [comment]
Ouff, that sure sounds like the correct decision!

**Comment by skenaja** [comment]
Closing issue for now - let me know if there is anything outstanding that requires a fix here. 

There is also a possible feature request that could come out this - I've added here - feel free to upvote/comment https://hicetnunc.featureupvote.com/suggestions/177097/collections-list-and-blacklisted-wallets
