### ISSUE TITLE
So many failing / pending transactions - what happens to these tez?

### ISSUE THREAD

**Issue by codewithfeeling** [hicetnunc2000/hicetnunc#391]
I am losing quite a lot of tez with transactions that don't complete (they stay on Pending) or I get a failure notice. In this case 6 tez have left my wallet, but 3 transactions have failed.

![image](https://user-images.githubusercontent.com/262516/113489906-d436f280-94be-11eb-8453-ebeb2b1f077f.png)

After 6 minutes:

![image](https://user-images.githubusercontent.com/262516/113489931-f92b6580-94be-11eb-83f2-217cc4a056eb.png)

![image](https://user-images.githubusercontent.com/262516/113490031-9be3e400-94bf-11eb-8e29-aa665e7cefc6.png)

What happens to these tezos?

**Comment by Quasimondo** [comment]
Looking at your general stats it looks to me like the majority of your transactions go through fine:
https://tzstats.com/tz1YJvMiZyXnzvV9pxtAiuCFvaG7XoBZhbUQ

But I also noticed more "backtracked" transactions than lets say 3 weeks ago and I would like to know why those happen - is it due to more general traffic or is there some miscalculation in the contract that tries to estimate the required gas fees for an operation?

Of course those "backtracked" or "failed" transactions are a bit annoying. As for losing tez - as far as I know all you can lose in this case is some part of the (low) gas fee depending on at which point of the operation the fail happened and how much of the gas has already been spent on computational resources. You can neither lose tokens nor tez that are being sent when that happens since all those will be returned to the sender.

**Comment by sombriodasilva** [comment]
I also had a few backtracked transactions yesterday. I haven't been able to mint anything yet because of that.

https://tzkt.io/tz1cXTbeSsxtCjQ5jqu3WubJQNvkSU9FzXji

**Comment by cdaein** [comment]
~My transactions have also been failing since yesterday, saying "storage quota exceeded", but the file size is 3.1MB. And I don't think I did anything different. Any guide would be much appreciated.
https://tzkt.io/oo7WgLWDEHfDraQZTF5bjSarVPTjFuBQFN4W4crmR9hFWjiKfN3~

I had similar problems of failing transactions a few times in a row. Read discord conversations and the general recommendation is just to try again a little later. This morning, after failing twice in a row, it worked the third time. Another thing I tried differently was to keep the file name shorter(!?).

**Comment by khuezy** [comment]
All of my transactions to swap the NFT are backtracked.

The error:
Storage quota exceeded for the operation
A script or one of its callee wrote more bytes than the operation said it would

**Comment by skenaja** [comment]
There's more info on backtracked transactions here:
https://github.com/hicetnunc2000/hicetnunc/wiki/Troubleshooting#i-got-storage-quota-exceeded-for-the-operation-error---what-happened

It's mostly down to the wallet software not being able to correctly estimate the amount of storage needed.
