### ISSUE TITLE
swap issue 

### ISSUE THREAD

**Issue by NFTScape** [hicetnunc2000/hicetnunc#393]
Hi, I'm tried to swap this objkt for resale. It appears to have disappeared from my collection. 

Operation group
ooa8RvNXvBcbxQkpdZL8bQJu3xmqp2Y3CkVPGX3ywnTDzchqKhy
Date & time
Apr 3, 3:53:47 PM
Block level
1413359
Status
Applied
Operation content (2)
Transaction content
Sender
tz1eRS4s2da82Lev6QqjTe6JcM3FzXQdYTcx
Counter
11983222
Baker fee
0.009931 ꜩ
Gas used
68352 / 96166 [71.1%]
Storage fee
0.02725 ꜩ
Storage used
109 / 109 [100.0%]
Allocation fee
0 ꜩ
Amount
0 ꜩ ($0.00)
Target
Hic et nunc Minter (KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9)
Status
Applied

**Comment by andrevenancio** [comment]
What's the objkt ID?

**Comment by NFTScape** [comment]
Here is one Objkt #16201

**Comment by NFTScape** [comment]
Here is the other one Objkt #13861

**Comment by yuradmt** [comment]
Have the same issue with objkt #3030.
No longer see it in my collection after listing.

https://www.hicetnunc.xyz/tz/tz1WJjnVE8UUdvyvF6vQ5XKTXajaDRtok3Yj

**Comment by skenaja** [comment]
When you swap a item for resale, under the hood it's transferred to the `Hic et Nunc Minter` account's collection (wallet address `KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9`) ready to be sold on your behalf which is why it no longer appears in your collection.

For the initial case logged by @NFTScape, you can see the objkt ID here (I searched by Operation Group) https://better-call.dev/mainnet/opg/ooa8RvNXvBcbxQkpdZL8bQJu3xmqp2Y3CkVPGX3ywnTDzchqKhy/contents

There's a related feature request to show swapped items on the Collections tab here:
https://hicetnunc.featureupvote.com/suggestions/175980/keep-swapped-collected-objkts-as-part-of-my-collection

**Comment by yuradmt** [comment]
Yeah, having a UI for managing your listed Objekts seems important. Definitely better than writing down my listed Objekt IDs on a piece of paper or something.

**Comment by NFTScape** [comment]
Right, that UI is important. Thanks for your response.
