### ISSUE TITLE
Keep the platform raw and minimalistic

### ISSUE THREAD

**Issue by djangobits** [hicetnunc2000/hicetnunc#40]
Hey,
in countless conversations it became obvious to me, that many people love the raw and minimalistic experience on the platform. They feel they are part of a chaotic new that was just born, they feel to be at the nex gen frontier. So while I am happy about improvements, functional and UX, I hope you all are aware of that. hicetnunc is a bit of mistery.... let's try to preserve that aura to some extent...

**Comment by djangobits** [comment]
Let me just collect a few opinions to make that point clear:

_"Part of the charm is obviously that the site is forever balancing on the cusp of total breakdown"_

_"This platform is extremely esoteric and confusing, but it also feels like you're participating in a performative Conceptual Art piece from the year 2050. 👍 Would recommend."_

_"yeah it's pretty weird over there...I like it"_

_"it's so out there I feel like I'm going to mess something up and lose money"_

_"honestly your site looks minimalist and it is, but I like it 1,000 more than opensea"_

**Comment by andrevenancio** [comment]
I agree. the platform minimalistic design is great. However there are some improvements that should be done in order to improve the experience and maintenance. those changes are not reflected on the design but rather on how the files are organised.

For example the Feed.js file that handles how the homepage feed looks, currently has only 2 media types. image or video. To expand on media types in the future we need to refactor the code to smaller modules so its easier to maintain and test.

But I agree. minimalistic design is 👍

**Comment by andrevenancio** [comment]
Closing this issue.
