### ISSUE TITLE
It should be possible to open links in a new tab from interactive OBJKTs

### ISSUE THREAD

**Issue by arielm** [hicetnunc2000/hicetnunc#406]
I have a [html-based OBJKT](https://www.hicetnunc.xyz/objkt/23180) which features a UI made of clickable links. The expected behaviour would be to have the links opened in a new tab, but it's currently not working.

The error obtained is:
> Blocked opening '<URL>' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.

Would it be possible to "allow popups"? I think it would be helpful in a lot of interactive OBJKTs.

Note: It's only about allowing popups generated via a click on the page (the browser won't allow popups if it's not initiated by a click event...)

**Comment by andrevenancio** [comment]
You created an NFT made in HTML. If on the NFT you are sending the user outside, you are no longer on the NFT. 

does that make sense?

HTML NFT are sandboxes for se security reasons. You cant't do everything you would be able to in a normal HTML file. And that's by design. If there's any questions in the future check out on Discord before minting. The HTML is meant to be used as a self contained piece.

**Comment by arielm** [comment]
The original NFT is still available in its own tab. So yes, I'm sending the user outside (by opening a new tab) but it's always possible to display the NFT by switching to the previous tab.

Real-world demonstration of the concept [here](https://chronotext.s3.amazonaws.com/ubu/v1.htm).
