### ISSUE TITLE
PROFILE DOES NOT ENTER

### ISSUE THREAD

**Issue by skitpixels** [hicetnunc2000/hicetnunc#470]
I do not understand programming, my profile does not enter and I am unable to sell my works.

link: https://www.hicetnunc.xyz/tz/tz1Pv9rsa2y78vUUtTBUejUR6kDK9WBrGL37

**Comment by djangobits** [comment]
Hello,
This was one of your tokens:

https://tzcomet.io/#/token/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/25761%3Falways-show-multimedia%3Dtrue

We found it offending if you consider how many LGBT lost their lives in WW2 in Hitler's concentration camps. There was an outcry of people on Twitter as well.

Can you explain what the deeper meaning of that piece was meant to be?

The community is meant to be as inclusive as possible what also means that nobody should feel offended because of his race, religion, gender or sexual orientation. Thus we decided to ban it until someone steps forward. Now is your time to explain.

**Comment by skenaja** [comment]
I'm going to close this for now, will re-open if new information is provided.
