### ISSUE TITLE
refused to connect to blob... because it it violates the document's content security policy

### ISSUE THREAD

**Issue by shig2k1** [hicetnunc2000/hicetnunc#481]
go to https://www.hicetnunc.xyz/objkt/30431

have a look at all the errors in the content about refusing to connect to blob

it works on safari, but not chrome or firefox

It's trying to load glb data into a blob - I gather that the blob data is being refused; I think it's because of the injected content-security-policy when serving the iframe

**Comment by shig2k1** [comment]
![image](https://user-images.githubusercontent.com/961015/114395462-4e890600-9b94-11eb-925d-58d2e8dbe64c.png)

**Comment by shig2k1** [comment]
![image](https://user-images.githubusercontent.com/961015/114409851-c65e2d00-9ba2-11eb-920f-e13f01d5da63.png)

**Comment by andrevenancio** [comment]
The html sandbox has a lot of security restrictions in order to keep the users as safe as possible from injecting 3rd party content (like external websites for example, or actually security issues by accessing the patent application). There's not much we can do to lift this restrictions without compromising the security of the platform which I hope you understand it's priority. The introduced the preview feature to avoid having people minting things that don't work. I suggest you try loading it in another way if possible.

**Comment by shig2k1** [comment]
you were able to make an exception for p5.js audio library - I wonder if the same change for script-src there will work for gltfloader for threejs ... otherwise maybe I'll try embedding them some other way :-/

**Comment by shig2k1** [comment]
I will find another way to do this; I think it's my preloader which causes the problem. I'm able to embed glbs and load them another way. I think I will create and share a guide once I've finished so others don't run into the same issue

**Comment by avoguga** [comment]
Is there a link to the guide? @shig2k1
