### ISSUE TITLE
"Item not for sale"

### ISSUE THREAD

**Issue by GOLDWAVVVES** [hicetnunc2000/hicetnunc#489]
"Item not for sale"
I uploaded 3 pieces to HicetNunc but all of them appear "not for sale" immediately after mint
and afterwards there's no option to change that
what to do?

**Comment by skenaja** [comment]
There have been intermittent periods of delays in the swap button appearing after minting due to an upstream data provider that aggregates and indexes blockchain transaction data. We're tracking this in #477.

If you're still experiencing issues with this, please can you add details there, including `tz...` wallet ID & objkt number
