### ISSUE TITLE
My hicetnunc collection doesn't show anymore

### ISSUE THREAD

**Issue by christophebruno** [hicetnunc2000/hicetnunc#544]
My hicetnunc page is down since yesterday. The nfts do not load anymore.
https://www.hicetnunc.xyz/tz/tz1PajQPa3aN8u4rRRQYbQCXFDidZkBKwje5
(The day before I burnt 2 nfts on 3, maybe the problem is related?)

**Comment by christophebruno** [comment]
ok, now it's back (???). But one of the nft I burnt is still online.
https://www.hicetnunc.xyz/objkt/29395
Can you check that please?

**Comment by skenaja** [comment]
Hi @christophebruno 

There were issues affecting HEN's data providers yesterday which affected the display of collection and creation pages. These are now resolved, and I can see your profile OK.

Regarding 29395, it's still swapped (on sale). You need to cancel the swap on the objkt's `swap` tab in order to burn it. The burn page will make this clearer in future.

Please add further comments if you still have problems, and I'll re-open the ticket.
