### ISSUE TITLE
I think I sold my tokens to myself...

### ISSUE THREAD

**Issue by Skyefyre502** [hicetnunc2000/hicetnunc#581]
I have no idea what happened.  

I minted 3 tokens. They said "Not For Sale." I went to KuKai Wallet and saw that I had 3 tokens to "send" somewhere... I figured it was a "swap to swap" deal, because it's not like there's any guide I can read that tells me how to get my item for sale. 

So I sent them from KuKai wallet to wherever this is: 
Transaction Hash
oowGzS8urHgW5mx7mWgMCWYA7X6HLnRfmDac1fHkC4tdSLiTVfY

Can anyone tell me if I should just burn these and start over? Did I just mint an NFT that I sold to someone else? Thanks.

**Comment by mescalina** [comment]
lol, dude what you just did I guess is unseen.
Basically you sent your token to the Hic Et Nunc smart contract address which now results as the owner of all 3 the editions.
No idea if they can send it back to you, I don't think so. Anyway now you cannot do anything, you can't swap or burn them cause you are not the owner anymore.
You should re-mint them. because you have a blank new address and this was your first mint you can open a new address, move your funds to the new one and restart with a clean slate :)
When you mint something you must put it for sale using the hen interface where you will see a SWAP button. you click it an input how many editions you want to put for sale and at what price. One you did it the HEN contract becomes the owner but you are recorded in the swap. The way you did it now there are no swaps recorded and you cant get them back.

**Comment by Skyefyre502** [comment]
Oh man, seriously?! There's nothing I can do? Not even contact them and ask them to send it back? 
I guess I'm just concerned with re-minting and them suing us for art that never was supposed to be theirs in the first place, you know?

**Comment by mescalina** [comment]
Don't worry, nobody is gonna sue you..

**Comment by Skyefyre502** [comment]
LOL Cool. So just to reiterate:  I should fill out a whole new form, get a new address, move my wallet to that, and start over?
What would happen if I just uploaded a different version of the object on the same account?  The one I posted was kind of a test, but I do want to have the option of deleting it, and since I cant do that unless they send it back to me, it's kinda stuck there on that address forever. Is that how this works?

**Comment by mescalina** [comment]
Consider the old one as burned, no one will have own it and you cannot see it anymore on the website. It's gone.
You can of course upload the same image to the account again, it will be a little confusing cause people will see it double but no harm is possible. You cant delete something you don't own anymore so it will stay there forever I guess.

PS. you should not use github for this kind of issues cause you end up creating caos in a contest that is for developing the source code.
There is the HEN discord channel for this kind of help requests :)

**Comment by skenaja** [comment]
Just to confirm that those objkts are permanently stuck on the HEN contract address, and can't be burned. 

There's a full guide to mint, swap, buy etc here: https://github.com/hicetnunc2000/hicetnunc/wiki
