### ISSUE TITLE
You can't burn something you don't own... this person owns 50 copies. so those don't belong to you

### ISSUE THREAD

**Issue by hulkiokantabak** [hicetnunc2000/hicetnunc#640]
You can't burn something you don't own... this person owns 50 copies. so those don't belong to you
https://www.hicetnunc.xyz/tz/tz1U4y37SnmE9SYzHE8aNPJDrJtcGtfD9MLN

_Originally posted by @andrevenancio in https://github.com/hicetnunc2000/hicetnunc/issues/639#issuecomment-831364300_

...

I don't know how you came to the conclusion but that is my Temple wallet. The name on the hic et nunc accountis mine as well.

So I am trying to burn from a wallet and get the error I reported.

I would appreciate if you can help.

**Comment by andrevenancio** [comment]
**Please don't create new issues, but instead re-open the issue you created**

So object [35323](https://www.hicetnunc.xyz/objkt/35323) was created by that wallet you mention. I've made a mistake in my reply I shouldn't have copied this `KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9` this is the current owner of those 50 copies. And that address is the hic et nunc minter. Which means your object is currently on a swap.

Objects on a swap can be purchased by anyone. and they can't be burned. If you want to burn them you need to cancel the swap so they move from the hicetcnunc minter back to your wallet.

This is explained on the WIKI page. You should really have a read through it before reporting expected behaviour as a bug.
https://github.com/hicetnunc2000/hicetnunc/wiki/How-to-burn-%F0%9F%94%A5

Hope that helps. Closing

**Comment by hulkiokantabak** [comment]
Thank you.
