### ISSUE TITLE
Onject disappeared from my collection when I tried to resell it

### ISSUE THREAD

**Issue by kidartprojects** [hicetnunc2000/hicetnunc#651]
**Describe the bug**
I attempted to SWAP an object I had just bought
**To Reproduce**
I am not very well versed in this. That didn't stop Hic Et Nunc from taking my money and letting me join. You should really document all these processes more. A lot of people have no idea what they are doing.

**Expected behavior**
I WANT THE NFT I PAID A LOT OF MONEY FOR TO BE IN MY COLLECTION

**Screenshots**
no idwa

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.
tz1hG3YfioQtFAV6bUcJjonf3vMLp3hQxHNv - wallet?
ooMUU3izECmEBZyBetJYtYW2UqmWrDqfGQvA3s2VSeqBHbtgUNV - operation hash from me buying the object?

**Comment by andrevenancio** [comment]
> I am not very well versed in this. That didn't stop Hic Et Nunc from taking my money and letting me join. You should really document all these processes more. A lot of people have no idea what they are doing.

Please read through the WIKI.
https://github.com/hicetnunc2000/hicetnunc/wiki

If there are still questions you can join Discord and ask any question there.

Going back to your question, it seems like you purchase a OBJKT and swap it. If you swap it, its no longer in your posession so it doesn't show on your `collection` because its in the market not on your collection. To show on your collection you need to cancel your swap.

Here's your current swaps:
OBJKT#59699 (2 at 3 tez each)
OBJKT#65476 (1 at 5 tez)
OBJKT#65585 (1 at 30tez)

Please be considerate and read the WIKI. It takes really long time to properly reply to questions here, and this is info that is available on the WIKI.
