### ISSUE TITLE
Interactive Objkts not scrollable

### ISSUE THREAD

**Issue by soyCarballeira** [hicetnunc2000/hicetnunc#665]
Objkts #70009 and #70034 are interactive, with more text than what fits in the viewing area. It doesn't show scrollbars and are not scrollable.

**To Reproduce**

1. Create an interactive OBJKT with a long text (to make it bigger than what fits in a screen)
2. Check Preview
3. Preview works fine and shows scrollbars
4. Mint it
5. Go to the OBJKT page
6. No scrollbars visible, also no scrolling via mouse wheel or keyboard arrows is possible, neither in regular nor in fullscreen mode.

**Expected behavior**
As issue #389  (closed more than a month ago), the final OBJKT should show a scrollbar and be scrollable

**Comment by andrevenancio** [comment]
The main reason HTML shouldn't have scrollbars is mainly because more often than none people write bad css and it generates tiny scrollbars. Specially on macos where the default is that scrollbars are hidden. So #389 was fixed by having the scrollbars disabled on the preview.

So the iframe should have overflow: hidden. It is up for the content creators to then do a container and add overflow-y: auto;

At the moment the iframe has scrollbars="no" which completely disables any scrollbars even if specified via css inside the html. I'm not sure why that is. @pichiste What do you think we can do here?

**Comment by pichiste** [comment]
Not sure why the `scrolling="no"` is there either tbh – probably a holdover from when the HTML OBJKTs were being displayed on the main feed, causing usability issues. Let's just remove it?

**Comment by pichiste** [comment]
PR here: https://github.com/hicetnunc2000/hicetnunc/pull/672 @andrevenancio 👀

**Comment by pichiste** [comment]
Closing since this will be fixed in next deployment
