### ISSUE TITLE
3D Models glitches

### ISSUE THREAD

**Issue by crzypatchwork** [hicetnunc2000/hicetnunc#716]
There are light weight glitched and some new glitches that appeared. The model viewer seems unstable and it's needed to find a version that can help stabilizing such displays.

**Comment by fraguada** [comment]
@crzypatchwork can you add any links objkts that are glitching? OS? Browser? Browser version? There could be many reasons for a component to glitch, but model-viewer on h=n and in other projects is pretty stable in my experience.

**Comment by andrevenancio** [comment]
model-viewer has been updated to version 1.7.0
https://github.com/google/model-viewer/releases

It would be nice to know exactly what the problem is. The comments I've seen on discord aren't really specific to what the problem is. The links I've seen, I see a 3d model loading.. not knowing how the 3d model should look I can't really identity what is bad. I suggest we revert to previous version.

So on `public/index.html` instead of

```
 <script
      type="module"
      src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
    ></script>
```

You would load
```
 <script
      type="module"
      src="https://unpkg.com/@google/model-viewer@1.6.0/dist/model-viewer.min.js"
    ></script>
```

**Comment by bebogp** [comment]
Some images that compose the 3D model (glb) are repeated and out of place and scale.
This should be only the cube, when I minted it last week it was ok https://www.hicetnunc.xyz/objkt/80566
Windows 10 Chrome Versión 90.0.4430.212 (Build oficial) (64 bits)

**Comment by matheusassuncao28** [comment]
I am also having problems with my glb. models https://www.hicetnunc.xyz/objkt/68981
image is repeated, with a different scale

**Comment by mrdoob** [comment]
There is a new point release that should fix these issues:
https://github.com/google/model-viewer/releases/tag/v1.7.1

**Comment by andrevenancio** [comment]
In theory there's no resolution needed. We're not specifying the version to load. So it will pick up that 1.7.1 once its released. Which it did looking by the 2 examples above.
